### PR TITLE
add a workspace Cargo.toml for building from root folder.

### PR DESCRIPTION
**Pull request by dhuseby**
Signed-off-by: Dave Huseby <dhuseby@linuxfoundation.org>

### CODE REVIEW

**Review by mikelodder7 — CHANGES_REQUESTED** [review]
Amcl and rustlibsecp256k1 are subprojects for libhl-crypto. We should move those if we want a single workspace

**Comment by dhuseby** [comment]
@mikelodder7 what about the rust folder under the repo root? What should we do with that?

**Comment by dhuseby** [comment]
@mikelodder7 updated PR.

**Review by mikelodder7 — APPROVED** [review]

**Comment by mikelodder7** [comment]
That is part of reconciling with the Sawtooth folks. Let’s talk with them first

**Pull request merged**
