### PR TITLE
Added release update process

### PR DESCRIPTION
**Pull request by mikelodder7**
Signed-off-by: Michael Lodder <redmike7@gmail.com>

### CODE REVIEW

**Comment by vaporos** [comment]
Is 'stable' the literal branch, or is there one 'stable' per major.minor release? If the former, how is supporting multiple release streams handled?

**Comment by mikelodder7** [comment]
How many release streams do you need?
Usually tagging the stable branch at each release is done and you can have any number of stable branches, for each stream. I’ve never neede more than one.

**Comment by vaporos** [comment]
Depends upon your commitment to the consumers of your library and duration of support for older versions. For something as foundational as this, I would expect fairly long-term support (in terms of critical/security fixes) and API-level backward-compatibility, with backports to older major versions. (See semver - https://semver.org/.)

**Comment by mikelodder7** [comment]
That’s pretty easy to manage with tags on stable

**Comment by vaporos** [comment]
Releasing 1.1.2, 2.0.1, 1.1.3, 2.0.2, 2.0.3, etc. in that order would require at least two branches be maintained (one with 1.1.x and the other with 2.0.x). Or are you force-pushing to 'stable'?

**Comment by mikelodder7** [comment]
I never force push. You could have two branches of stable in that case for each version. Maybe it would be best to label the stable branches as stable_1.x.x and stable_2.x.x

**Comment by dcmiddle** [comment]
So the evolved version I'm getting from the comment stream is that we would have a master branch and release branches.  Release branches would be ~permanent. We would not delete them after the release. All other branches would be ephemeral (and probably uncommon).

**Pull request closed without merging**
